// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuslqjhadyagruclflhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1c2xxamhhZHlhZ3J1Y2xmbGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODUzNzgsImV4cCI6MjA2NjY2MTM3OH0.m6f2OfBWykcYPy0XBw5lwKiW48hLUso-7KKNaJi9cts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);